### ISSUE TITLE
max, min and step are required props now

### ISSUE THREAD

**Issue by plagerweij** [freddie-nelson/vue3-slider#10] opened 2021-04-07 12:45 UTC
The `max`, `min`, and `step` props are now required. This is not mentioned in the README file.

When I don't explicitly use them, like so:
```vue
<vue3-slider v-model="myNumber" />
```

I get these warnings:
```
[Vue warn]: Missing required prop: "max"
[Vue warn]: Missing required prop: "min"
[Vue warn]: Missing required prop: "step"
```

I'm using:
vue **3.0.11**
vue3-slider **1.5.6**

**Comment by freddie-nelson** [comment] 2021-04-07 14:46
I was not able to reproduce this bug, however I have removed the required attributes from these props as they already have default values. So this edge case should be fixed in 1.5.7

**Closed as completed by freddie-nelson** 2021-04-07 14:46 UTC
