### ISSUE TITLE
slider doesn't update if modelValue is changed externally

### ISSUE THREAD

**Issue by plagerweij** [freddie-nelson/vue3-slider#9] opened 2021-04-07 12:39 UTC
Same code and problem as #5, but now I'm using vue **3.0.11** and vue3-slider **1.5.6**

**Comment by freddie-nelson** [comment] 2021-04-07 15:11
I am unable to reproduce this bug, is there anything else that could be affecting this on your end?

**Comment by plagerweij** [comment] 2021-04-07 15:28
I'm not sure and I think I'm out of my depth here. I'm using the exact same code example as before. Other things I can mention are:

I'm using:
Nodejs **15.14.0**
npm **7.7.6**
Firefox **87.0**
Chrome **89.0.4389.114**

I'll [attach](https://github.com/freddie-nelson/vue3-slider/files/6272727/package-json-files.zip) my `package.json` and `package-lock.json` files if that helps.

If there's anything else I should share, let me know.

**Comment by freddie-nelson** [comment] 2021-04-07 15:34
Try deleting your node_modules folder and reinstalling your dependencies. 

Not sure if this will fix your issue but it might if somehow a previous version of vue3-slider has been installed

**Comment by plagerweij** [comment] 2021-04-07 15:39
Did not work. When I inspect the [node_modules/vue3-slider/package.json](https://github.com/freddie-nelson/vue3-slider/files/6272796/package.json.zip) file I have it says it's version **1.5.6**

**Comment by plagerweij** [comment] 2021-04-07 15:44
Maybe it's helpful to mention that I do not seem to have this problem when I downgrade to version **1.5.5**

**Comment by freddie-nelson** [comment] 2021-04-07 15:49
1.5.7 just released, you could try upgrading and see if it fixes your issue

**Comment by plagerweij** [comment] 2021-04-07 15:58
Unfortunately not. I've also now tested if there maybe was a problem with my development version, but that also does not seem the case. Both `npm run serve` and `npm run build` result in the same problem.

**Comment by plagerweij** [comment] 2021-04-07 16:13
I'm out of ideas at the moment. Here's my [entire project](https://github.com/freddie-nelson/vue3-slider/files/6273028/slider-test.zip) folder with version **1.5.7** excluding dependencies. Maybe this helps with reproducing.

**Comment by freddie-nelson** [comment] 2021-04-08 18:48
I am able to reproduce the bug with your project files and I will begin to look into this

**Comment by freddie-nelson** [comment] 2021-04-08 19:07
I have discovered that the bug only occurs in the production build of the component, hence why I could not reproduce the issue on my development build. 

Really sorry about this, completely my mistake and I'll work to find a solution 👍

**Comment by plagerweij** [comment] 2021-04-08 19:23
All good. Thanks for looking into it.

**Comment by freddie-nelson** [comment] 2021-04-08 19:35
The issue should be fixed in 1.5.8

Turned out the issue was that I was importing from "@vue/runtime-core" in useModelValue.ts and useDragHandler.ts instead of "vue".

I honestly can't believe I missed this cause it was also causing the production build to be 300kb. I'll try my best to not make silly errors like this again however, we are all human so I can't promise anything 😆.

Really sorry again that this caused so much trouble, if you could verify on your end that everything works accordingly then I will close this issue

**Comment by plagerweij** [comment] 2021-04-08 19:50
1.5.8 works. Thanks for fixing it, bugs can be sneaky.

**Closed as completed** 2021-04-08 19:51 UTC
